function simple_WCS
% SIMPLE_WCS Select a data set from the pop-up menu, then
% 
% 
   SS = get(0,'screensize');
   width = SS(3);
   height = SS(4);

   %  Create and then hide the UI as it is being constructed.
   f1 = figure('Visible','off', ...
       'MenuBar', 'none', ...
       'Name', 'WebCam Selection', ...
       'NumberTitle', 'off', ...
       'Position',[width/3 height/3 width/3 height/3]);
   info = imaqhwinfo;
   instAdap = info.InstalledAdaptors;
   
   htext = uicontrol('Style','text', ...
           'String','Which adapter are you wanting to use?',...
           'Position',[width/9, height/6, width/9, height/9]);
   hpopup = uicontrol('Style','popupmenu',...
           'String',instAdap,...
           'Position',[width/9, height/6-1,150,15]);
   hpush = uicontrol('Style', 'pushbutton', ...
           'String', 'Continue', ...
           'Position', [width/9, height/9, 150,15]);
       
   align([htext,hpopup, hpush],'Distribute','Distribute');
   
   %Make the UI visible.
   f1.Visible = 'on';
   
   %
   % Get data from drop down menu, store it, close figure
   %
   
   waitfor(f1);
   
   f2 = figure('Visible','off', ...
       'MenuBar', 'none', ...
       'Name', 'WebCam Selection', ...
       'NumberTitle', 'off', ...
       'Position',[width/3 height/3 width/3 height/3]);
   
   
   htext = uicontrol('Style','text', ...
           'String','Which adapter are you wanting to use?',...
           'Position',[width/9, height/6, width/9, height/9]);
   hpopup = uicontrol('Style','popupmenu',...
           'String',instAdap,...
           'Position',[width/9, height/6-1,150,15]);
   hpush = uicontrol('Style', 'pushbutton', ...
           'String', 'Continue', ...
           'Position', [width/9, height/9, 150,15]);
       
   align([htext,hpopup, hpush],'Distribute','Distribute');
   
   %Make the UI visible.
   f2.Visible = 'on';
   
   
end

